In [1]:
pip install beautifulsoup4

Collecting beautifulsoup4
  Downloading beautifulsoup4-4.15.0-py3-none-any.whl.metadata (3.8 kB)
Collecting soupsieve>=1.6.1 (from beautifulsoup4)
  Using cached soupsieve-2.8.4-py3-none-any.whl.metadata (4.6 kB)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\dev\dp_312\.venv\lib\site-packages (from beautifulsoup4) (4.15.0)
Downloading beautifulsoup4-4.15.0-py3-none-any.whl (109 kB)
Using cached soupsieve-2.8.4-py3-none-any.whl (37 kB)
Installing collected packages: soupsieve, beautifulsoup4
Successfully installed beautifulsoup4-4.15.0 soupsieve-2.8.4
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 26.1.2
[notice] To update, run: C:\DEV\dp_312\.venv\Scripts\python.exe -m pip install --upgrade pip

In [3]:
import pandas as pd
URL = 'datasets/한국전력거래소_지역별 시간별 태양광 및 풍력 발전량_20231130.csv'
sunlight = pd.read_csv(URL,encoding='euc-kr')
sunlight.head()

         거래일자  거래시간  지역명  태양광발전량(Mwh)  풍력발전량(Mwh)
0  2023-09-01     1  경기도     0.029757         0.0
1  2023-09-01     2  경기도     0.000000         0.0
2  2023-09-01     3  경기도     0.000000         0.0
3  2023-09-01     4  경기도     0.000000         0.0
4  2023-09-01     5  경기도     0.000000         0.0

In [4]:
sunlight.tail()

             거래일자  거래시간  지역명  태양광발전량(Mwh)  풍력발전량(Mwh)
37123  2023-11-30    20  부산시     3.121764         0.0
37124  2023-11-30    21  부산시     2.427456         0.0
37125  2023-11-30    22  부산시     0.612640         0.0
37126  2023-11-30    23  부산시     0.070920         0.0
37127  2023-11-30    24  부산시     0.009600         0.0

In [5]:
sunlight #print(sunlight)

             거래일자  거래시간  지역명  태양광발전량(Mwh)  풍력발전량(Mwh)
0      2023-09-01     1  경기도     0.029757         0.0
1      2023-09-01     2  경기도     0.000000         0.0
2      2023-09-01     3  경기도     0.000000         0.0
3      2023-09-01     4  경기도     0.000000         0.0
4      2023-09-01     5  경기도     0.000000         0.0
...           ...   ...  ...          ...         ...
37123  2023-11-30    20  부산시     3.121764         0.0
37124  2023-11-30    21  부산시     2.427456         0.0
37125  2023-11-30    22  부산시     0.612640         0.0
37126  2023-11-30    23  부산시     0.070920         0.0
37127  2023-11-30    24  부산시     0.009600         0.0

[37128 rows x 5 columns]